#!/usr/bin/env sh

set -e

ROOT_DIR=$(pwd)
TEMP_DIR="$ROOT_DIR/tmp"
BUILD_DIR="$TEMP_DIR/swagger-codegen"
GEM_NAME='easybill-rest-client'
SOURCE_DIR="$BUILD_DIR/$GEM_NAME"
TARGET_DIR="$TEMP_DIR/$GEM_NAME"

[ -e $TARGET_DIR ] && rm -r $TARGET_DIR
mkdir -p $TEMP_DIR

if [ ! -e $BUILD_DIR ]
then
  git clone https://github.com/swagger-api/swagger-codegen $BUILD_DIR
fi
cp config.json $BUILD_DIR
cp swagger.json $BUILD_DIR
cd $BUILD_DIR
./run-in-docker.sh mvn package
./run-in-docker.sh generate -i swagger.json \
                            -l ruby \
                            -o $GEM_NAME \
                            -c config.json

cp -r $SOURCE_DIR $TARGET_DIR

# Change permissions of created files since they are owned by root.
docker run -it \
            -w /gen \
            -v "$BUILD_DIR:/gen" \
            maven:3-jdk-7 \
            chmod 777 -R .

rm -rf $BUILD_DIR
